### ISSUE TITLE
I cannot run Learn.

### ISSUE THREAD

**Issue by tzvipittinsky** [learn-co-curriculum/first-lab#16]
I successfully submitted the Lab but "LOCAL BUILD
Run tests in your local environment." is not checked off since whenever I run learn in Terminal I get the following message: -bash: learn: command not found

**Comment by dfenjves** [comment]
Hi @tzvipittinsky - I'm just seeing this. Were you able to resolve this issue?

**Comment by tzvipittinsky** [comment]
Yes, all good now.
