### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by JoanBrownCS** [learn-co-curriculum/first-lab#18]
I am just getting started in the Teaching Fellowship, but thought you would want my fresh-eyes impressions before I understand the whole system and interaction among systems.
I am a little confused about whether I am in the "teacher fellowship" part or the "student" content at any given point in time. I am happy, and thrilled even, to work through the student content so that I know exactly what they have to do. But I would really like some distinction shown when I look at the progress topics/folders on the left side of the learn website.
Also, the introductory pages I worked through said I would just use learn commands in Nitrous, but then once I got to the second instance of the First-Lab (student view), all the directions were for using Git commands. Not a problem, because I would like to learn as much as possible, just knowing what the students are expected to use seems to be more appropriate for what the teachers should also learn, right?
Then, once in the student version of the First-Lab, the instructions talk about the "Terminal" which is available on Mac computers, but doesn't seem to be available on a PC. The instructions also talk about using git clone and pasting the SSH url. But opening Nitrous from the top menu bar takes care of the "Terminal" and "git clone" issue all at once. Further, if when I thought to open Nitrous and actually type git clone and try to paste the SSH url, Ctrl-V doesn't work. I noticed that other student/teachers were having the same issue. I took a break to think about the overall structure of your systems and their interactions and was finally able to piece it together. Today when I had time again, I was able to complete the lab quickly.
Lastly, when I began using learn, somehow I was started partway through the folder/topic list on the left. Once I noticed that I had blank circles before my current location, I went back and filled in. The content I did out of order would have been better done in order. The welcome letter, the overview of the system, etc.
I don't think it's a bad thing to have to reason through a problem, and I might have missed a detail or two that would have made things quicker for me, but thought these were some difficulties and discrepancies that you would like to know more about.

**Comment by dfenjves** [comment]
@JoanBrownCS - Thank you so much for these comprehensive notes. I'm going to go back and do a thorough review of the intro unit based on your feedback. I'm really glad that we have such proactive and thoughtful folks working through the fellowship.
