### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by elkhattabi82** [learn-co-curriculum/first-lab#19]
I am getting an error message when I try to use git clone. Here is the message, what should I do?

Sanaas-MBP:labs Nanati$ git clone git@github.com:elkhattabi82/first-lab-teacher-fellowship-1015.git
Cloning into 'first-lab-teacher-fellowship-1015'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Sanaas-MBP:labs Nanati$ git clone git@github.com:elkhattabi82/first-lab-teacher-fellowship-1015.git
Cloning into 'first-lab-teacher-fellowship-1015'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by pletcher** [comment]
You'll need to make sure that your SSH keys are configured correctly. Instructions are [here](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/). (You can skip the part about generating a key since you probably already have one.)
