### ISSUE TITLE
Error running Learn

### ISSUE THREAD

**Issue by Dom-Mc** [learn-co-curriculum/first-lab#23]
I received the following error after running `learn`

`Could not find proper version of rspec-core (3.4.4) in any of the sources`
`Run `bundle install` to install missing gems.`

After running the install, the test past even though I hadn't yet created any additional files (required in the lab).

**Comment by AnnJohn** [comment]
thanks for raising this @Dom-Mc. We'll fix this soon so that the test fails. 

@mendelB can you look into this one and prioritize it?
