### ISSUE TITLE
I've forked the lab but its not showing up

### ISSUE THREAD

**Issue by NYCLondon** [learn-co-curriculum/first-lab#27]
I forked the lab (the blue forked lab is showing) but when i go to cd first-lab-001 terminal says "no such file or directory'

What should I do?

**Comment by jmarvin-e** [comment]
Having the same problem. Did you figure out a solution?

**Comment by jmarvin-e** [comment]
I figured it out. You need to use the whole directory name which is unclear in the instructions. The command line follows.

cd first-lab-001-prework-ios

**Comment by JessRudder** [comment]
@NYCLondon  try `cd first-lab-001-prework-ios`  I believe the -000 was for the initial public version.  If you look in your github repositories, you'll see that your version of the lab was forked as -001-prework-ios.

The instructions were:

```
Go into this lab's directory by typing cd LABNAME (where "LABNAME" is the name of your version of this lab — we might type, e.g. cd first-lab-000). Confirm that your working directory in terminal is this lab by typing: pwd
```

In this case `cd first-lab-000` was an example, not the exact thing you should type to get it to work with your version of the lab.
