### ISSUE TITLE
Unclear instructions in 5. OPENING A PULL REQUEST

### ISSUE THREAD

**Issue by gentb** [learn-co-curriculum/first-lab#28]
The instructions in the README say, in regards to submitting a pull request, "to do this, in Learn click on the title of the lab to go to your fork on GitHub" and "then click the green Pull Request button." 

While these written instructions seem to be correct, the corresponding images do not show a student's fork (previous images before the pull request section do) but instead show a pull request on the learn-co-curriculum repo.

**Comment by aviflombaum** [comment]
Yep, we're re-writing this lab but that's a good point - the GitHub icon only turns into your fork after you fork, if you reload the page.
