### ISSUE TITLE
No such directory error when changing directory to "cd first-lab-000"

### ISSUE THREAD

**Issue by jmarvin-e** [learn-co-curriculum/first-lab#30]

**Comment by JessRudder** [comment]
@je6789 try `cd first-lab-001-prework-ios`  I believe the -000 was for the initial public version.  If you look in your github repositories, you'll see that your version of the lab was forked as -001-prework-ios.

The instructions were:

```
Go into this lab's directory by typing cd LABNAME (where "LABNAME" is the name of your version of this lab — we might type, e.g. cd first-lab-000). Confirm that your working directory in terminal is this lab by typing: pwd
```

In this case `cd first-lab-000` was an example, not the exact thing you should type to get it to work with your version of the lab.
