### ISSUE TITLE
There is no Title here to fork.  Do you mean the "View" button?

### ISSUE THREAD

**Issue by dpinkus** [learn-co-curriculum/first-lab#9]
To get started, in Learn click the title of the lab to go to Flatiron School's copy of the lab on Github.

**Comment by matbalez** [comment]
Good catch. This is referencing a now-stale version of the UI. We need to update the screenshot & instruction. 

@aviflombaum

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by matbalez** [comment]
Note: this needs to come out of the icebox and be fixed before Sept 28.

**Comment by AnnJohn** [comment]
@matbalez noted. We should be looking at iceboxed issues next week and assigning dates then. Thanks.
